# Generated by Django 5.1.7 on 2026-04-04 03:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_id', models.CharField(max_length=20, unique=True, verbose_name='规则ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('description', models.TextField(verbose_name='规则描述')),
                ('rule_type', models.CharField(choices=[('required', '必填项'), ('forbidden', '禁止项'), ('numeric', '数值检查'), ('format', '格式检查'), ('logic', '逻辑检查')], max_length=20, verbose_name='规则类型')),
                ('severity', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], max_length=20, verbose_name='严重等级')),
                ('rule_config', models.JSONField(default=dict, verbose_name='规则配置')),
                ('keywords', models.JSONField(default=list, verbose_name='关键词')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '检查规则',
                'verbose_name_plural': '检查规则',
                'db_table': 'check_rules',
            },
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='模板描述')),
                ('content', models.TextField(verbose_name='模板内容')),
                ('template_type', models.CharField(default='rental', max_length=50, verbose_name='模板类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '合同模板',
                'verbose_name_plural': '合同模板',
                'db_table': 'contract_templates',
            },
        ),
        migrations.CreateModel(
            name='LegalKnowledge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('law_type', models.CharField(max_length=50, verbose_name='法律类型')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='适用地区')),
                ('vector_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='向量ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '法律知识',
                'verbose_name_plural': '法律知识',
                'db_table': 'legal_knowledge',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='合同标题')),
                ('landlord_info', models.JSONField(default=dict, verbose_name='出租方信息')),
                ('tenant_info', models.JSONField(default=dict, verbose_name='承租方信息')),
                ('property_info', models.JSONField(default=dict, verbose_name='房屋信息')),
                ('lease_info', models.JSONField(default=dict, verbose_name='租赁信息')),
                ('payment_info', models.JSONField(default=dict, verbose_name='支付信息')),
                ('other_terms', models.JSONField(default=dict, verbose_name='其他条款')),
                ('content', models.TextField(blank=True, null=True, verbose_name='合同内容')),
                ('check_result', models.JSONField(blank=True, default=dict, null=True, verbose_name='审查结果')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('generated', '已生成'), ('checked', '已审查'), ('modified', '已修改'), ('final', '最终版')], default='draft', max_length=20, verbose_name='状态')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='文件路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '合同',
                'verbose_name_plural': '合同',
                'db_table': 'contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=100, verbose_name='对话主题')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('collected_info', models.JSONField(default=dict, verbose_name='已收集信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='myapp.contract', verbose_name='关联合同')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '对话记录',
                'verbose_name_plural': '对话记录',
                'db_table': 'conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('user', '用户'), ('assistant', '助手'), ('system', '系统')], max_length=20, verbose_name='消息类型')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('extracted_entities', models.JSONField(blank=True, default=dict, null=True, verbose_name='提取的实体')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='myapp.conversation', verbose_name='对话')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('avatar', models.URLField(blank=True, null=True, verbose_name='头像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户扩展信息',
                'verbose_name_plural': '用户扩展信息',
                'db_table': 'user_profiles',
            },
        ),
    ]
