# Generated by Django 5.1.7 on 2026-04-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_contracts_generated',
            field=models.IntegerField(default=0, verbose_name='生成合同总数'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_contracts_checked',
            field=models.IntegerField(default=0, verbose_name='检查合同总数'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_contracts_saved',
            field=models.IntegerField(default=0, verbose_name='保存合同总数'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_contracts_exported',
            field=models.IntegerField(default=0, verbose_name='导出合同总数'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_conversations',
            field=models.IntegerField(default=0, verbose_name='对话次数'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_messages',
            field=models.IntegerField(default=0, verbose_name='消息总数'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_activity_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最后活动时间'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_used_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='首次使用时间'),
        ),
    ]
