# Generated by Django 5.1.7 on 2026-04-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userprofile_usagestats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.TextField(blank=True, null=True, verbose_name='头像(base64)'),
        ),
    ]
