# Generated by Django 5.1.7 on 2026-04-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_message_conversation_alter_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='total_contracts_exported',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_conversations',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_messages',
        ),
    ]
