# Generated by Django 5.1.7 on 2026-04-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_message_conversation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='total_contracts_saved',
        ),
    ]
