# Generated by Django 5.1.7 on 2026-04-04 13:52

from django.db import migrations
from django.db import connection


def safe_delete_model(apps, schema_editor):
    """安全删除模型，即使表不存在也不会报错"""
    # 检查Message表是否存在
    with connection.cursor() as cursor:
        cursor.execute("SHOW TABLES LIKE 'myapp_message'")
        message_table_exists = cursor.fetchone() is not None
        
        cursor.execute("SHOW TABLES LIKE 'myapp_conversation'")
        conversation_table_exists = cursor.fetchone() is not None
    
    # 如果表存在，再执行删除操作
    if message_table_exists:
        with connection.cursor() as cursor:
            cursor.execute("DROP TABLE IF EXISTS myapp_message CASCADE")
    
    if conversation_table_exists:
        with connection.cursor() as cursor:
            cursor.execute("DROP TABLE IF EXISTS myapp_conversation CASCADE")


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_message_conversation_and_more'),
    ]

    operations = [
        migrations.RunPython(safe_delete_model, migrations.RunPython.noop),
    ]
