# Generated by Django 5.1.7 on 2026-04-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_message_conversation_delete_conversation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='check_result',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='landlord_info',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='lease_info',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='other_terms',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='payment_info',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='property_info',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='tenant_info',
        ),
    ]
