# Generated by Django 5.1.7 on 2026-04-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_message_conversation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalClause',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='条款标题')),
                ('content', models.TextField(verbose_name='条款内容')),
                ('type', models.CharField(max_length=50, verbose_name='法律类型')),
                ('area', models.CharField(max_length=50, verbose_name='适用地区')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '法律条款',
                'verbose_name_plural': '法律条款',
                'db_table': 'legal_clauses',
            },
        ),
    ]
