# Generated by Django 5.1.7 on 2026-04-05 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_legalclause_delete_contracttemplate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContractTemplate',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='LegalKnowledge',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
